##
## Description: this container is used to run an express based app
##
## Author: Jorge Cabane <jcabane@ripley.com>
##

version: '3.1'
services:

  redis:
    image: redis:latest
    container_name: cache
    networks:
      - web
  node:
    env_file:
      - .env
    build: ./
    image: express/express-seed-nodejs-12.x:12.13.1-alpine3.10
    working_dir: /app
    command: npm run start:full
    restart: always
    networks:
      - web
    links:
      - redis
    volumes:
      - ./:/app
    ports:
      - "3120:4000"

networks:
  web:
    external:
      name: react-seed_webgateway
